### ISSUE TITLE
failed to build when upgrade kernel

### ISSUE THREAD

**Issue by st0nie** [MrDuartePT/mrduarte-ebuilds#1]
[build.log](https://github.com/MrDuartePT/mrduarte-ebuilds/files/11835557/build.log)

**Comment by st0nie** [comment]
![图片](https://github.com/MrDuartePT/mrduarte-ebuilds/assets/42872734/72481a35-4de2-4903-a1d6-1d30bcd9df68)

fixed

**Comment by MrDuartePT** [comment]
It funny in my system and my friend system dosen’t have that error
