### ISSUE TITLE
[guru] failed to build when upgrade kernel

### ISSUE THREAD

**Issue by st0nie** [MrDuartePT/mrduarte-ebuilds#3]
the same as #1
 KERNELVERSION=${KV_FULL} without export

**Comment by st0nie** [comment]
seems you need to export it
like v4l2loopback
![image](https://github.com/MrDuartePT/mrduarte-ebuilds/assets/42872734/2367efeb-a403-4b91-aad0-409feab1976a)

**Comment by st0nie** [comment]
like v4l2loopback
![image](https://github.com/MrDuartePT/mrduarte-ebuilds/assets/42872734/2367efeb-a403-4b91-aad0-409feab1976a)

**Comment by MrDuartePT** [comment]
Ok I we fixed later for now just edit the ebuild yourself and use until guru is updated. 
But strange on my system compile without any problem.

**Comment by MrDuartePT** [comment]
@st0nie i updated the ebuild verify if is solve?

**Comment by st0nie** [comment]
resolved

**Comment by st0nie** [comment]
Why I haven't seen any difference on guru/dev ?
https://cgit.gentoo.org/repo/proj/guru.git/tree/sys-firmware/lenovolegionlinux/lenovolegionlinux-9999.ebuild?h=dev

**Comment by st0nie** [comment]
![image](https://github.com/MrDuartePT/mrduarte-ebuilds/assets/42872734/cccbf1f4-4ac7-43d3-bdce-078ee7169ff8)
this should be:
```
export KERNELVERSION=${KV_FULL}
linux-mod-r1_src_compile
```

**Comment by st0nie** [comment]
If not, it will get the version of the kernel that the machine is using now, not the one specified by `eselect kernel set`

**Comment by st0nie** [comment]
I don't have access to guru-dev right now, can you please do this for me? Thanks in advance!

**Comment by MrDuartePT** [comment]
Well I notice that I did change but for some reason git failed to push and I didn’t notice I will push it today. I need to reinstall the system last week and still don’t have time to verify everthing (SELinux relabing break my btrfs root qgroup)

**Comment by MrDuartePT** [comment]
I did the change now:
https://gitweb.gentoo.org/repo/proj/guru.git/patch/sys-firmware/lenovolegionlinux/lenovolegionlinux-9999.ebuild?id=fea07b47a71ba248dcc6ca05edd89c07305b54d9
